package com.calisthenia.core.model

object ExerciseCatalog {
    val exercises: List<ExerciseDetail> = listOf(
        ExerciseDetail(
            id = "flexiones-basicas",
            name = "Flexiones cl?sicas",
            description = "Flexi?n de codos en posici?n de plancha para fortalecer pecho y tr?ceps.",
            muscleGroups = listOf(MuscleGroup.CHEST, MuscleGroup.SHOULDERS, MuscleGroup.ARMS, MuscleGroup.CORE),
            difficulty = ExerciseDifficulty.BEGINNER,
            equipment = Equipment.BODYWEIGHT,
            focus = TrainingFocus.UPPER_BODY,
            tips = listOf(
                "Mant?n el cuerpo alineado de cabeza a talones",
                "Apoya las manos justo debajo de los hombros",
                "Controla la bajada en 3 segundos para maximizar el tiempo bajo tensi?n",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1517836357463-d25dfeac3438",
        ),
        ExerciseDetail(
            id = "dominadas-pronadas",
            name = "Dominadas pronadas",
            description = "Tracci?n vertical con agarre pronado enfocada en dorsales y b?ceps.",
            muscleGroups = listOf(MuscleGroup.BACK, MuscleGroup.SHOULDERS, MuscleGroup.ARMS),
            difficulty = ExerciseDifficulty.INTERMEDIATE,
            equipment = Equipment.BARRA,
            focus = TrainingFocus.UPPER_BODY,
            tips = listOf(
                "Activa el core y evita balanceos",
                "Inicia el movimiento retrayendo las esc?pulas",
                "Piensa en llevar el pecho hacia la barra",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1598970434795-0c54fe7c0642",
        ),
        ExerciseDetail(
            id = "remadoras-invertidas",
            name = "Remo invertido en barra",
            description = "Tracci?n horizontal controlada con el peso corporal.",
            muscleGroups = listOf(MuscleGroup.BACK, MuscleGroup.ARMS, MuscleGroup.CORE),
            difficulty = ExerciseDifficulty.BEGINNER,
            equipment = Equipment.BARRA,
            focus = TrainingFocus.UPPER_BODY,
            tips = listOf(
                "Mant?n la cadera alineada con los hombros",
                "Aprieta esc?pulas en la parte alta",
                "Controla la bajada para trabajar estabilidad",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1605296867720-8d45a65b85b2",
        ),
        ExerciseDetail(
            id = "sentadillas-libres",
            name = "Sentadillas al aire",
            description = "Flexi?n y extensi?n de cadera y rodillas para fortalecer tren inferior.",
            muscleGroups = listOf(MuscleGroup.LEGS, MuscleGroup.CORE),
            difficulty = ExerciseDifficulty.BEGINNER,
            equipment = Equipment.BODYWEIGHT,
            focus = TrainingFocus.LOWER_BODY,
            tips = listOf(
                "Empuja las rodillas ligeramente hacia afuera",
                "Mant?n el pecho erguido y la espalda neutra",
                "Profundiza hasta que los muslos queden paralelos al piso",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1546484499-ebb3820f67f8",
        ),
        ExerciseDetail(
            id = "pistol-squat-asistida",
            name = "Sentadilla pistol asistida",
            description = "Variaci?n unilateral para fortalecer piernas y estabilidad.",
            muscleGroups = listOf(MuscleGroup.LEGS, MuscleGroup.CORE),
            difficulty = ExerciseDifficulty.ADVANCED,
            equipment = Equipment.BODYWEIGHT,
            focus = TrainingFocus.LOWER_BODY,
            tips = listOf(
                "Usa un soporte ligero para mantener el equilibrio",
                "Desciende controlando la rodilla alineada con el pie",
                "Activa gl?teo y core durante toda la fase exc?ntrica",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1526402464735-76c5c07f75dd",
        ),
        ExerciseDetail(
            id = "plancha-prona",
            name = "Plancha prona",
            description = "Ejercicio isom?trico para la musculatura profunda del core.",
            muscleGroups = listOf(MuscleGroup.CORE, MuscleGroup.SHOULDERS),
            difficulty = ExerciseDifficulty.BEGINNER,
            equipment = Equipment.BODYWEIGHT,
            focus = TrainingFocus.CORE,
            tips = listOf(
                "Empuja el suelo con antebrazos y separa esc?pulas",
                "Mant?n gl?teos y abdomen contra?dos",
                "Evita colapsar la zona lumbar",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1598970434795-0c54fe7c0642",
        ),
        ExerciseDetail(
            id = "hollow-hold",
            name = "Hollow hold",
            description = "Sost?n isom?trico para construir un core fuerte y estable.",
            muscleGroups = listOf(MuscleGroup.CORE),
            difficulty = ExerciseDifficulty.INTERMEDIATE,
            equipment = Equipment.BODYWEIGHT,
            focus = TrainingFocus.CORE,
            tips = listOf(
                "Apoya la zona lumbar completamente en el suelo",
                "Extiende brazos y piernas alineados con el torso",
                "Respira profundo manteniendo la tensi?n",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1514996937319-344454492b37",
        ),
        ExerciseDetail(
            id = "elevaciones-pierna-colgando",
            name = "Elevaciones de pierna colgando",
            description = "Flexi?n de cadera colgando para trabajar recto abdominal y flexores.",
            muscleGroups = listOf(MuscleGroup.CORE, MuscleGroup.LEGS),
            difficulty = ExerciseDifficulty.INTERMEDIATE,
            equipment = Equipment.BARRA,
            focus = TrainingFocus.CORE,
            tips = listOf(
                "Evita balanceos, controla el descenso",
                "Eleva hasta sentir contracci?n m?xima en el abdomen",
                "Cierra costillas y mant?n esc?pulas deprimidas",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1594737625785-c66858a24b47",
        ),
        ExerciseDetail(
            id = "fondos-paralelas",
            name = "Fondos en paralelas",
            description = "Empuje vertical para tr?ceps, pecho y hombros.",
            muscleGroups = listOf(MuscleGroup.CHEST, MuscleGroup.SHOULDERS, MuscleGroup.ARMS),
            difficulty = ExerciseDifficulty.INTERMEDIATE,
            equipment = Equipment.PARALELAS,
            focus = TrainingFocus.UPPER_BODY,
            tips = listOf(
                "Inclina ligeramente el torso para activar pecho",
                "Mant?n codos pegados al cuerpo para enfatizar tr?ceps",
                "Baja hasta 90? sin perder control",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1534367610401-9f5ed68180aa",
        ),
        ExerciseDetail(
            id = "pike-pushup",
            name = "Flexiones en pica",
            description = "Empuje vertical con peso corporal que enfatiza hombros y trapecio.",
            muscleGroups = listOf(MuscleGroup.SHOULDERS, MuscleGroup.ARMS, MuscleGroup.CORE),
            difficulty = ExerciseDifficulty.INTERMEDIATE,
            equipment = Equipment.BODYWEIGHT,
            focus = TrainingFocus.UPPER_BODY,
            tips = listOf(
                "Forma una V invertida con cadera elevada",
                "Flexiona codos apuntando hacia atr?s",
                "Empuja fuerte con tr?ceps al extender",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1583454110551-21f2fa2f2050",
        ),
        ExerciseDetail(
            id = "dragon-flag",
            name = "Dragon flag",
            description = "Movimiento avanzado para core y control corporal global.",
            muscleGroups = listOf(MuscleGroup.CORE, MuscleGroup.BACK, MuscleGroup.LEGS),
            difficulty = ExerciseDifficulty.ADVANCED,
            equipment = Equipment.ESPALDERA,
            focus = TrainingFocus.CORE,
            tips = listOf(
                "Mant?n el cuerpo r?gido como una tabla",
                "Desciende lento manteniendo control lumbar",
                "Progr?salo con rangos parciales",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b",
        ),
        ExerciseDetail(
            id = "llevar-rodillas-al-pecho",
            name = "Mountain climbers controlados",
            description = "Trabajo metab?lico de core y estabilidad escapular.",
            muscleGroups = listOf(MuscleGroup.CORE, MuscleGroup.FULL_BODY, MuscleGroup.ARMS),
            difficulty = ExerciseDifficulty.BEGINNER,
            equipment = Equipment.BODYWEIGHT,
            focus = TrainingFocus.FULL_BODY,
            tips = listOf(
                "Mant?n hombros alineados con mu?ecas",
                "Lleva rodillas al pecho sin elevar cadera",
                "Controla la respiraci?n mientras alternas",
            ),
            mediaUrl = "https://images.unsplash.com/photo-1556817411-31ae72fa3ea0",
        ),
    )
}

object RecipeCatalog {
    val recipes: List<Recipe> = listOf(
        Recipe(
            id = "avena-proteica-manana",
            title = "Taz?n de avena proteica",
            description = "Avena cremosa con prote?na, mantequilla de man? y frutos rojos.",
            mealType = MealType.DESAYUNO,
            prepTimeMinutes = 5,
            cookTimeMinutes = 5,
            servings = 1,
            ingredients = listOf(
                RecipeIngredient("Avena en hojuelas", "60 g"),
                RecipeIngredient("Leche entera o bebida vegetal", "250 ml"),
                RecipeIngredient("Prote?na en polvo sabor vainilla", "1 scoop"),
                RecipeIngredient("Mantequilla de man?", "1 cucharada"),
                RecipeIngredient("Frutos rojos congelados", "1/2 taza"),
                RecipeIngredient("Semillas de ch?a", "1 cucharadita"),
            ),
            steps = listOf(
                "Calienta la leche y a?ade la avena, cocina 3-4 minutos.",
                "Mezcla la prote?na al final para evitar grumos.",
                "Sirve en un taz?n y finaliza con mantequilla de man?, frutos rojos y ch?a.",
            ),
            macros = NutritionInfo(calories = 615, protein = 34.0, carbs = 68.0, fats = 22.0),
            imageUrl = "https://images.unsplash.com/photo-1551183053-bf91a1d81141",
        ),
        Recipe(
            id = "pollo-camote-horno",
            title = "Pollo al horno con camote y verduras",
            description = "Comida completa rica en prote?na y carbohidratos de liberaci?n lenta.",
            mealType = MealType.COMIDA,
            prepTimeMinutes = 15,
            cookTimeMinutes = 35,
            servings = 2,
            ingredients = listOf(
                RecipeIngredient("Pechuga de pollo", "400 g"),
                RecipeIngredient("Camote", "2 medianos"),
                RecipeIngredient("Pimiento rojo", "1 pieza"),
                RecipeIngredient("Calabacita", "1 pieza"),
                RecipeIngredient("Aceite de oliva", "1.5 cucharadas"),
                RecipeIngredient("Piment?n, ajo en polvo, sal y pimienta", "al gusto"),
            ),
            steps = listOf(
                "Precalienta el horno a 200 ?C.",
                "Corta camote y verduras en cubos, mezcla con aceite y especias.",
                "Hornea todo en charola por 35 minutos, volteando a mitad del tiempo.",
            ),
            macros = NutritionInfo(calories = 680, protein = 55.0, carbs = 68.0, fats = 24.0),
            imageUrl = "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
        ),
        Recipe(
            id = "wrap-atun-cremoso",
            title = "Wrap de at?n cremoso",
            description = "Wrap alto en prote?na ideal para almuerzo r?pido.",
            mealType = MealType.COMIDA,
            prepTimeMinutes = 10,
            cookTimeMinutes = 0,
            servings = 1,
            ingredients = listOf(
                RecipeIngredient("Tortilla integral grande", "1 pieza"),
                RecipeIngredient("At?n en agua escurrido", "1 lata"),
                RecipeIngredient("Yogur griego natural", "2 cucharadas"),
                RecipeIngredient("Aguacate", "1/2 pieza"),
                RecipeIngredient("Espinaca fresca", "1 taza"),
                RecipeIngredient("Jugo de lim?n y pimienta", "al gusto"),
            ),
            steps = listOf(
                "Mezcla el at?n con yogur, lim?n y pimienta.",
                "Unta el aguacate sobre la tortilla y a?ade la mezcla de at?n.",
                "Agrega espinaca, enrolla firme y corta a la mitad.",
            ),
            macros = NutritionInfo(calories = 520, protein = 42.0, carbs = 48.0, fats = 18.0),
            imageUrl = "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe",
        ),
        Recipe(
            id = "ensalada-quinoa-garbanzos",
            title = "Ensalada templada de quinoa y garbanzos",
            description = "Plato vegetal con buen aporte de prote?nas y fibra.",
            mealType = MealType.CENA,
            prepTimeMinutes = 15,
            cookTimeMinutes = 15,
            servings = 2,
            ingredients = listOf(
                RecipeIngredient("Quinoa", "120 g"),
                RecipeIngredient("Garbanzos cocidos", "1 taza"),
                RecipeIngredient("Pepino", "1/2 taza en cubos"),
                RecipeIngredient("Tomate cherry", "1 taza"),
                RecipeIngredient("Aceite de oliva", "1 cucharada"),
                RecipeIngredient("Jugo de lim?n", "2 cucharadas"),
                RecipeIngredient("Perejil picado", "2 cucharadas"),
            ),
            steps = listOf(
                "Cuece la quinoa en agua con sal por 12 minutos y deja reposar.",
                "Mezcla en un bowl la quinoa con garbanzos y vegetales.",
                "Ali?a con aceite, lim?n, sal y perejil picado.",
            ),
            macros = NutritionInfo(calories = 480, protein = 20.0, carbs = 66.0, fats = 14.0),
            imageUrl = "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85",
        ),
        Recipe(
            id = "panqueques-avena-banana",
            title = "Panqueques de avena y pl?tano",
            description = "Desayuno esponjoso y nutritivo para comenzar con energ?a.",
            mealType = MealType.DESAYUNO,
            prepTimeMinutes = 8,
            cookTimeMinutes = 12,
            servings = 2,
            ingredients = listOf(
                RecipeIngredient("Avena molida", "90 g"),
                RecipeIngredient("Pl?tano maduro", "1 pieza"),
                RecipeIngredient("Huevos", "2 piezas"),
                RecipeIngredient("Polvo para hornear", "1 cucharadita"),
                RecipeIngredient("Canela", "1/2 cucharadita"),
                RecipeIngredient("Yogur griego", "2 cucharadas para servir"),
            ),
            steps = listOf(
                "Lic?a avena, pl?tano, huevos, polvo para hornear y canela.",
                "Vierte porciones en sart?n antiadherente a fuego medio.",
                "Cocina 2-3 minutos por lado y acompa?a con yogur.",
            ),
            macros = NutritionInfo(calories = 560, protein = 28.0, carbs = 65.0, fats = 19.0),
            imageUrl = "https://images.unsplash.com/photo-1508739773434-c26b3d09e071",
        ),
        Recipe(
            id = "batido-tropical-gana-masa",
            title = "Smoothie tropical cal?rico",
            description = "Batido denso en calor?as para complementar tu super?vit.",
            mealType = MealType.BATIDO,
            prepTimeMinutes = 5,
            cookTimeMinutes = 0,
            servings = 1,
            ingredients = listOf(
                RecipeIngredient("Leche de coco light", "250 ml"),
                RecipeIngredient("Mango congelado", "1 taza"),
                RecipeIngredient("Pi?a congelada", "1/2 taza"),
                RecipeIngredient("Prote?na en polvo sabor coco", "1 scoop"),
                RecipeIngredient("Avena molida", "30 g"),
                RecipeIngredient("Semillas de lino", "1 cucharada"),
            ),
            steps = listOf(
                "Lic?a todos los ingredientes hasta obtener textura cremosa.",
                "Sirve fr?o y consume de inmediato.",
            ),
            macros = NutritionInfo(calories = 610, protein = 32.0, carbs = 72.0, fats = 20.0),
            imageUrl = "https://images.unsplash.com/photo-1514996937319-344454492b37",
        ),
        Recipe(
            id = "huevos-revueltos-aguacate",
            title = "Huevos revueltos con aguacate y tostadas",
            description = "Desayuno r?pido con grasas saludables y prote?na completa.",
            mealType = MealType.DESAYUNO,
            prepTimeMinutes = 7,
            cookTimeMinutes = 6,
            servings = 1,
            ingredients = listOf(
                RecipeIngredient("Huevos", "3 piezas"),
                RecipeIngredient("Claras adicionales", "2 piezas"),
                RecipeIngredient("Aguacate", "1/2 pieza"),
                RecipeIngredient("Tostadas integrales", "2 rebanadas"),
                RecipeIngredient("Aceite de oliva", "1 cucharadita"),
                RecipeIngredient("Sal, pimienta y ceboll?n", "al gusto"),
            ),
            steps = listOf(
                "Bate huevos y claras con sal y pimienta.",
                "Cocina a fuego medio con aceite hasta textura cremosa.",
                "Sirve con aguacate en l?minas sobre las tostadas y espolvorea ceboll?n.",
            ),
            macros = NutritionInfo(calories = 540, protein = 34.0, carbs = 32.0, fats = 28.0),
            imageUrl = "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43",
        ),
        Recipe(
            id = "arroz-integral-carne-magra",
            title = "Arroz integral con res magra y vegetales",
            description = "Comida potente para reponer energ?a posentrenamiento.",
            mealType = MealType.CENA,
            prepTimeMinutes = 15,
            cookTimeMinutes = 30,
            servings = 3,
            ingredients = listOf(
                RecipeIngredient("Arroz integral", "180 g"),
                RecipeIngredient("Carne molida magra (90/10)", "400 g"),
                RecipeIngredient("Zanahoria rallada", "1 taza"),
                RecipeIngredient("Ch?charos", "1 taza"),
                RecipeIngredient("Salsa de soya baja en sodio", "2 cucharadas"),
                RecipeIngredient("Jengibre rallado", "1 cucharadita"),
            ),
            steps = listOf(
                "Cuece el arroz integral siguiendo las instrucciones del paquete.",
                "Saltea la carne con jengibre hasta que est? dorada.",
                "A?ade vegetales y salsa de soya, mezcla con el arroz y cocina 3 minutos m?s.",
            ),
            macros = NutritionInfo(calories = 690, protein = 42.0, carbs = 78.0, fats = 20.0),
            imageUrl = "https://images.unsplash.com/photo-1512058564366-18510be2db19",
        ),
    )
}
